version: '3.8'

services:

  # Mariadb Service
  mariadb:
    image: mariadb:latest
    container_name: mariadb_tmeunier_cdn_database
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: tmeunier-cdn
      MYSQL_USER: tmeunier-cdn
      MYSQL_PASSWORD: tmeunier-cdn
      MYSQL_ROOT_PASSWORD: tmeunier-cdn
    volumes:
      - ./storage-db:/var/lib/mysql/
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app_network

# Docker Networks
networks:
  app_network:
    driver: bridge